- name: Futureproof
  ansible.builtin.apt:
    name: python3-passlib
    state: present
  become: true
  # Do i install this on the Node or the ansible_host?


- name: Change user password in Vagrant
  ansible.builtin.user:
    name: "{{ new_user }}"
    password: "{{ new_password | password_hash('sha512', 'tmpsalt') }}"
  become: true
# works:    password: "{{ 'u' | password_hash('sha512', 'tmpsalt') }}"
